### ISSUE TITLE
Current temperature sensor

### ISSUE THREAD

**Issue by Elkropac** [mathieu-mp/homeassistant-intex-spa#36]
Hi,
do you think there should be "current temperature" sensor, so you can create graphs easily? Maybe as a disabled entityby default?

I wanted to make graph and ended using template sensor
```
template:
  - sensor:
      - name: "spa_temperature"
        state: "{{ state_attr('climate.spa', 'current_temperature') | round(1) }}"
        unit_of_measurement: "°C"
```

Works for me.

If you find separate sensor useful, i can try to make it as PR
