### ISSUE TITLE
Current temperature auto up to date

### ISSUE THREAD

**Issue by Geoff-Hz** [mathieu-mp/homeassistant-intex-spa#42]
Hi, 
Thanks for this amazing apps.

I realise that current temperature is not updating automaticaly. To check it, I have to modify the desired temp and then current temp is changing.

How can I do to have a check every 10 minutes?
Regard,
Geoff

**Comment by mathieu-mp** [comment]
Hi @Geoff-Hz, I'm pleased to read your greatings !

The current temperature is expected to update after each command set, and automatically every 30 seconds.
To understand why it does not work on your side:
- could you enable logging, in your Home Assistant `config/configuration.yaml`:
```yaml
logger:
  default: warning # 'warning' is the default value
  logs:
    custom_components.intex_spa: debug
    intex_spa: debug
```
- and copy/paste some logs here:
  - Next to a command and its received response
  - During 2 idle minutes
