### ISSUE TITLE
Missing idle state for heater

### ISSUE THREAD

**Issue by jaroslav-fedor-swi** [mathieu-mp/homeassistant-intex-spa#46]
**Is your feature request related to a problem? Please describe.**

With current implementation you don't see how long the heater runs in order to keep target temperature. It is shown as it heat all time when it is on.

**Describe the solution you'd like**

When target temp is achieved, thermostat gets to idle state.

**Describe alternatives you've considered**

Template switch and climate can get this functionality:
```
switch
  - platform: template
    switches:
      spa_heat:
        value_template: "{{ is_state('climate.spa', 'heat') }}"
        turn_on:
          service: climate.turn_on
          target:
            entity_id: climate.spa
        turn_off:
          service: climate.turn_off
          target:
            entity_id: climate.spa
climate:
  - platform: generic_thermostat
    name: SPA_Custom
    heater: switch.spa_heat
    target_sensor: sensor.spa_current_temperature
    max_temp: 40
    min_temp: 20
    target_temp: 37
    precision: 1
```
