### ISSUE TITLE
Suggest a dashboard configuration in README

### ISSUE THREAD

**Issue by mathieu-mp** [mathieu-mp/homeassistant-intex-spa#7]
- [x] Discuss the point
- [ ] Update the README

**Comment by mathieu-mp** [comment]
Option A:
![image](https://user-images.githubusercontent.com/8644213/174648906-3b5181b2-cf5f-445f-ae71-696b6764d662.png)

```yaml
square: false
columns: 2
type: grid
cards:
  - type: entities
    entities:
      - type: section
        label: Confort
      - entity: switch.spa_jets
        name: Jets
      - entity: switch.spa_bubbles
        name: Bubbles
      - type: section
        label: Entretien
      - entity: switch.spa_power
        name: Power
      - entity: switch.spa_filter
        name: Filter
      - entity: switch.spa_sanitizer
        name: Sanitizer
    title: Spa
    show_header_toggle: false
  - type: thermostat
    entity: climate.spa_climate
    name: Chauffe
```

**Comment by mathieu-mp** [comment]
Option B:
![image](https://user-images.githubusercontent.com/8644213/174649032-0f8467f6-cd62-4d8c-af08-8026794e63fd.png)
```yaml
type: vertical-stack
cards:
  - type: entities
    entities: []
    title: Spa
  - type: thermostat
    entity: climate.spa_climate
    name: ' '
  - type: entities
    entities:
      - entity: switch.spa_jets
      - entity: switch.spa_bubbles
  - type: entities
    entities:
      - entity: switch.spa_power
      - entity: switch.spa_filter
      - entity: switch.spa_sanitizer
```
